### ISSUE TITLE
Old 3DS Support?

### ISSUE THREAD

**Issue by Shinyhunter2109** [popcorn9499/Ledybot#18]
Hey i found your version of Ledybot i would like to know if this version works for old3ds aswell ? excactly the special button feature works this with old 3ds?

**Comment by popcorn9499** [comment]
honestly no clue. possibly? its worth trying at least. if the version this is forked from doesnt work with the old 3ds then this one wont

**Comment by popcorn9499** [comment]
i mean the special buttons use rosalina input redirection

**Comment by Shinyhunter2109** [comment]
I tried it and the version works with the old 3ds the only thing i havent tested yet is the special buttons. I will test the buttons now and check if they work

**Comment by popcorn9499** [comment]
the only thing not mentioned cuz the wiki is sorta a Work in progress but. anyways, API Settings tab. Then clck add connection. (it is possible to host ledychat on a different device however not recommended) if you need the port changed or have please make sure u change the port on there and then hit add connection, This should work let me know if u need more help

**Comment by Shinyhunter2109** [comment]
Okay i tried the thing you mentioned but it doesnt connect ip is correct and port is in the general.json file i already have the newest version from your ledybot and ledychat. Is it maybe possible that you can create a section in the ledybot who people can add a twitch bot to perform the trade queue and fc adding thing when the have problems with ledychat. The trade queue feature is really cool and i want to use it on my Stream when it works :)

**Comment by popcorn9499** [comment]
ok question and this is my fault for not putting this in before sorta forgot to but. does this help? https://github.com/popcorn9499/ledyChat/wiki

**Comment by popcorn9499** [comment]
ledychat is a addon for chatbot. chatbot handles all the stuff with fcs and shit. some of the features still havent gotten pushed to the master repo but im working to make sure they are all stable atm

**Comment by Shinyhunter2109** [comment]
ok i tested it but it will not work the bot wont connect to my stream on twitch also the python file closes imideatly when i open it is that normal? I havent use python that much but every file that is needed for it closes imideatly :(

**Comment by Shinyhunter2109** [comment]
Also a thing that i saw is that in the newest version of ledybot when i disable the trade queue the bot dont trade pokemon to the people on the gts. I checked my files and everything is in the giveaway details maybe is this a bug idk

**Comment by popcorn9499** [comment]
> ok i tested it but it will not work the bot wont connect to my stream on twitch also the python file closes imideatly when i open it is that normal? I havent use python that much but every file that is needed for it closes imideatly :(

how are u opening python?




> Also a thing that i saw is that in the newest version of ledybot when i disable the trade queue the bot dont trade pokemon to the people on the gts. I checked my files and everything is in the giveaway details maybe is this a bug idk

that idk what was being done there. its really ya.... idk i never wrote that initial code. its been in there all along the tradequeue thing i just set an enable button to it. to be clear that tradequeue shit has been in the code since the bot was forked and i should probably either remove it or fix it.

**Comment by Shinyhunter2109** [comment]
i double click on the python file and than i opends and after that imediatly close it

**Comment by popcorn9499** [comment]
ill add something to the repo for u. ur running from windows correct?

**Comment by Shinyhunter2109** [comment]
yes

**Comment by popcorn9499** [comment]
you installed the packages required from pip?

**Comment by popcorn9499** [comment]
if not ill just roll it into this

**Comment by popcorn9499** [comment]
here download this specific file. it should contain the way to start that program. a easier method at least. just go put this in the chatbot folder then click it
chatbot should start loading

**Comment by popcorn9499** [comment]
working on the documentation is one thing i need to do

**Comment by Shinyhunter2109** [comment]
yea i will test it now and then i will tell you how its working thank you for your time :)

**Comment by popcorn9499** [comment]
ya no problem. would love to know if it works. if you need help just ask

**Comment by Shinyhunter2109** [comment]
ok now i followed all the steps you told me and the batch file opens normal and stays open maybe i have some mistakes in the files when i choose irc on the auth folder and the bot will not connect. i disabled all other plattforms like youtube and discord. At the folder chatbot i am also confused who i have to write what to get the irc thing for twitch to work on can you help me :)

**Comment by popcorn9499** [comment]
discord atm is a hard coded requirement
